# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cbcd0ed3c0890ec20f5ea2a0ab734dd2315e45f055d1e676a3f9d9713814d99f0a0320c496df9eaf33666bad4e473dbbd654104a0653cb75b09e6cbd6b813ce

test:
  secret_key_base: 74c6cb48e0f6d50186b45a94792227d9dbba143c2f90d905c043ddf3e08cf02853a49d394462380bac829bd8f67ab14cfc88c9810c90d0c69f8928a414e3e410

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
